persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Authentication par certificats uniquement (mTLS)
# password_file /mosquitto/config/passwd  # Desactive - auth par certificat
allow_anonymous true  # Pas de password requis, uniquement certificat client

# Port Standard (Non-secure)
listener 1883

# Port Websocket (Non-secure)
listener 9001
protocol websockets

# Secure MQTT listener (mTLS - Authentification Mutuelle)
listener 8883
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
tls_version tlsv1.2
require_certificate true