persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Autoriser les connexions anonymes (Pour le test initial)
# Une fois que ça marche, passe à "false" et configure un password
allow_anonymous true

# Écouter sur le port standard (0.0.0.0 permet l'accès extérieur)
listener 1883 0.0.0.0

# Listener Websocket (Optionnel, utile pour certains outils web)
listener 9001 0.0.0.0
protocol websockets