persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Global authentication
password_file /mosquitto/config/passwd
allow_anonymous false

# Port Standard (Non-secure)
listener 1883

# Port Websocket (Non-secure)
listener 9001
protocol websockets

# Secure MQTT listener (TLS simple - pas mTLS)
listener 8883
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
tls_version tlsv1.2
require_certificate false